# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

sirene:
  token: "VOTRE_TOKEN_ICI"  # Remplacez par votre token SIRENE
